version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks: 
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/financial_app_db

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks: 
      - app-network
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: ./frontend/financial-app-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks: 
      - app-network
    volumes:
      - ./frontend/financial-app-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: