apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <your-backend-image>:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017/financial_app_db
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devops-project
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: LoadBalancer